Make slice bound safe
warpdotdev/font-kit pull request #2
Opened 2021-10-07 22:12 UTC by kevinyang372

Fixes WAR-1432

**Info**
This PR does not change how we load the font -- the cause for the panic is probably because users have corrupted / non-standard font header files which do not report accurate length of the font collection. The font-kit library current loads files assuming these length information will be correct and thus when these assumptions turn out to be false, the loading will panic because of the out of bounds error on slicing. 

**Change**
Add type safe slicing which returns an error when index out of bounds rather than panicking.

2021-10-08 01:02 UTC, charlespierce requested changes
Some suggestions to make this a little more idiomatic.

Is this something that we can upstream? It seems like a poor experience for everyone if it can panic (rather than returning an error) when the Font file isn't in an expected format. Or is this related to code that we added in the fork in the first place?

2021-10-08 01:02 UTC, charlespierce commented on src/loaders/core_text.rs
>      let offset_table_pos = (&data[offset_table_pos_pos..]).read_u32::<BigEndian>()? as usize;
Rather than doing a check and returning if the value is out of range, can we instead use [`[T]::get`](https://doc.rust-lang.org/std/primitive.slice.html#method.get) to retrieve an `Option`, and then use `Option::ok_or` to convert it into a `Result`? Doing the operation and handling an error is generally more idiomatic in Rust, as opposed to checking first and then panicking. So that would make this look something like:

```rust
let offset_table_pos = data.get(offset_table_pos_pos..).ok_or(FontLoadingError::Parse).read_u32::<BigEndian>()? as usize;
```

2021-10-08 01:02 UTC, charlespierce commented on src/loaders/core_text.rs
> +    }
Similarly here, we can use `get` and `ok_or` to simplify this a bit:

```rust
slice.get(start..).ok_or(FontLoadingError::Parse)
```

Also, since this doesn't depend on data captured from the parent scope, can we make this into a helper function at the top level, rather than nesting it within the `unpack_data_fork_font` method?

2021-10-08 01:02 UTC, charlespierce commented on src/loaders/core_text.rs
> +        (get_slice_from_start(&data, map_offset + 28)?).read_u16::<BigEndian>()? as usize + 1;
For each of these (and elsewhere throughout this file), since there's a function now, I don't believe we need the extra parentheses:

```rust
let map_offset = get_slice_from_start(&data, 4)?.read_u32::<BigEndian>()? as usize;
```

2021-10-08 14:08 UTC, alokedesai commented
> Some suggestions to make this a little more idiomatic.
> 
> Is this something that we can upstream? It seems like a poor experience for everyone if it can panic (rather than returning an error) when the Font file isn't in an expected format. Or is this related to code that we added in the fork in the first place?

+1 to trying to fix this upstream (as well as the other fixes we've made in this library)

2021-10-08 16:24 UTC, kevinyang372 commented on src/loaders/core_text.rs
>      let offset_table_pos = (&data[offset_table_pos_pos..]).read_u32::<BigEndian>()? as usize;
Thanks! That's very helpful!

2021-10-08 16:24 UTC, kevinyang372 commented on src/loaders/core_text.rs
> +    }
Done!

2021-10-08 16:24 UTC, kevinyang372 commented on src/loaders/core_text.rs
> +        (get_slice_from_start(&data, map_offset + 28)?).read_u16::<BigEndian>()? as usize + 1;
Done!

2021-10-08 16:26 UTC, kevinyang372 commented
> Some suggestions to make this a little more idiomatic.
> 
> Is this something that we can upstream? It seems like a poor experience for everyone if it can panic (rather than returning an error) when the Font file isn't in an expected format. Or is this related to code that we added in the fork in the first place?

Makes sense! Will open a PR there as well. Not sure how long it will take for them to merge it tho

2021-10-11 18:12 UTC, charlespierce approved these changes
LGTM!

2021-10-11 18:34 UTC, merged